name: dart_date
description: Date manipulation library. DateTime extensions. Also includes an Interval object.
version: 1.3.2
homepage: https://github.com/xantiagoma/dart_date

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ">=0.17.0 <0.20.0"
  timeago: ^3.0.2

dev_dependencies:
  test: ^1.16.0
